title: Ryan's Dev Blog
description: ""
baseurl: ""
url: http://rhendric.github.io
permalink: /posts/:year/:month/:title
timezone: America/New_York
date_format: "%Y %b %-d"
kramdown:
  smart_quotes: apos,apos,quot,quot
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
    values:
      layout: default